spring:
  application:
    name: gateway
  datasource:
    url: jdbc:h2:mem:auth
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true


server:
  port: 7000

jwt:
  secret: secretshimbhu$77$kumawat~skking99

