spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  config:
    import: "optional:configserver:"
  datasource:
    url: jdbc:h2:mem:auth
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 7000

jwt:
  secret: eyJzdWIiOiAidXNlcjEyMyIsICJpYXQiOiAxNjI3NTY0ODAwLCAiZXhwIjogMTYyNzU2ODQwMH0c3BsaW50ZXIgY2VsbCBjb252aWN0aW9uICwgcHJpbmNlIG9mIHBlcnNpYSB3YXJyaW9yIHdpdGhpbg==


