spring:
  cloud:
    sidecar:
      port: 3000
      health-uri: /health
      accept-all-ssl-certificates: true
  application:
    name: customer-ms

  config:
    import: configserver:http://localhost:8888

server:
  port: 8600

sidecar:
  port: 3000
  health-uri: http://localhost:3000/health



